# Generated by Django 5.2 on 2025-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_number", models.IntegerField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("birth_date", models.DateField()),
                ("joining_date", models.DateField()),
                ("department", models.CharField(max_length=50)),
            ],
        ),
    ]
